import pytest
import lesson36a

seq = 'ATGGAGAACAACGAAGCCCCCTCCCCCTCGGGATCCAACAACAACGAGAACAACAATGCAGCCCAGAAGAAGCTGCAGCAGACCCAAGCCAAGGTGGACGAGGTGGTCGGGATTATGCGTGTGAACGTGGAGAAGGTCCTGGAGCGGGACCAGAAGCTATCGGAACTGGGCGAGCGTGCGGATCAGCTGGAGCAGGGAGCATCCCAGTTCGAGCAGCAGGCCGGCAAGCTGAAGCGCAAGCAATGGTGGGCCAACATGAAGATGATGATCATTCTGGGCGTGATAGCCGTTGTGCTGCTCATCATCGTTCTGGTGTCGCTTTTCAATTGA'

def test_find_codon():
    assert lesson36a.find_codon_lesson6('ATG', seq)== 0
    assert lesson36a.find_codon_lesson6('AAT', seq)== 54
    assert lesson36a.find_codon_lesson6('TGT', seq)== -1
    assert lesson36a.find_codon_lesson6('TGC', seq)== -1


    #pytest.raises(RuntimeError, "lesson35.n_neg('Z')")
